#!/bin/sh

mkdir -p /var/modep/lv2
chmod 2775 /var/modep
chmod 2775 /var/modep/lv2

chown -R modep:modep /var/modep

find /var/modep -type d -exec chmod 775 {} +
find /var/modep -type f -exec chmod 664 {} +

chmod 500 /etc/authbind/byport/80
chown modep:modep /etc/authbind/byport/80

#DEBHELPER#
